# Generated by Django 5.2.15 on 2026-06-24 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_runlogline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='run',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('scraper',), name='uniq_running_run_per_scraper'),
        ),
    ]
