# Generated by Django 5.2.15 on 2026-06-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_run_uniq_running_run_per_scraper'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='errors_csv',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='run',
            name='requests_csv',
            field=models.TextField(blank=True),
        ),
    ]
