# Generated by Django 5.2.15 on 2026-06-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_seed_hard_scrapers'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='claude_api_key',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
