# Generated by Django 5.2.15 on 2026-06-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_scraper_claude_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='login_password',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='scraper',
            name='login_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
