# Generated by Django 5.2.15 on 2026-06-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_scraper_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='max_tries',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
