# Generated by Django 5.2.15 on 2026-06-26 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_scraper_max_tries'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_hash', models.CharField(max_length=64, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('date_norm', models.CharField(blank=True, db_index=True, max_length=32)),
                ('tournament_name', models.CharField(blank=True, max_length=300)),
                ('draw_name', models.CharField(blank=True, max_length=120)),
                ('draw_gender', models.CharField(blank=True, max_length=20)),
                ('winner_team', models.CharField(blank=True, max_length=200)),
                ('loser_team', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('scrape', 'Scrape'), ('import', 'Import')], default='scrape', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('first_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inserted_matches', to='accounts.run')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_co_created_13eae8_idx')],
            },
        ),
    ]
