# Generated by Django 5.2.15 on 2026-06-27 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_scrapermodelfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('num_results', models.IntegerField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.run')),
                ('scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sa_keys', to='accounts.scraper')),
            ],
            options={
                'ordering': ['status', 'tournament_key'],
                'indexes': [models.Index(fields=['scraper', 'status'], name='accounts_sa_scraper_feaa89_idx')],
            },
        ),
    ]
