# Generated by Django 5.2.15 on 2026-06-24 01:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=120)),
                ('tour', models.CharField(max_length=60)),
                ('domain', models.CharField(max_length=120)),
                ('vendor_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('returns', models.CharField(default='CSV', max_length=12)),
                ('tournaments', models.JSONField(blank=True, default=list)),
                ('mode', models.CharField(choices=[('production', 'Production'), ('maintenance', 'Maintenance')], default='production', max_length=12)),
                ('maintenance_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tournament', models.CharField(default='All tournaments', max_length=120)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('running', 'Running')], default='success', max_length=12)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('output_size_bytes', models.PositiveIntegerField(default=0)),
                ('log_text', models.TextField(blank=True)),
                ('csv_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('launched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to=settings.AUTH_USER_MODEL)),
                ('scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='accounts.scraper')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['scraper', '-started_at'], name='accounts_ru_scraper_b798c1_idx'), models.Index(fields=['uuid'], name='accounts_ru_uuid_10198d_idx'), models.Index(fields=['status'], name='accounts_ru_status_ceef1d_idx')],
            },
        ),
    ]
