# Generated by Django 5.2.15 on 2026-06-24 02:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_scrapers'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunLogLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('level', models.CharField(default='INFO', max_length=8)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_lines', to='accounts.run')),
            ],
            options={
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['run', 'seq'], name='accounts_ru_run_id_20fec9_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'seq'), name='uniq_run_logline_seq')],
            },
        ),
    ]
