# Generated by Django 5.2.15 on 2026-06-24 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_run_errors_csv_run_requests_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('residential', 'Residential'), ('datacenter', 'Datacenter'), ('mobile', 'Mobile'), ('isp', 'ISP')], default='residential', max_length=16)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'proxies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scraper',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrapers', to='accounts.proxy'),
        ),
    ]
