# Generated by Django 5.2.15 on 2026-06-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_scraper_threads'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='pid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('running', 'Running'), ('stopped', 'Stopped')], default='success', max_length=12),
        ),
    ]
