# Generated by Django 5.2.15 on 2026-06-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_scraper_login_password_scraper_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='secret_value',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
