# Generated by Django 5.2.15 on 2026-06-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_scraper_secret_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='code',
            field=models.CharField(max_length=16),
        ),
    ]
