# Generated by Django 5.2.15 on 2026-06-26 22:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_collegematch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Monthly')], default='daily', max_length=12)),
                ('time_of_day', models.TimeField(default=datetime.time(6, 0))),
                ('weekday', models.PositiveSmallIntegerField(default=0)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('anchor_date', models.DateField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.run')),
                ('scraper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='accounts.scraper')),
            ],
            options={
                'indexes': [models.Index(fields=['enabled', 'next_run_at'], name='accounts_sc_enabled_f03679_idx')],
            },
        ),
    ]
