# Generated by Django 5.2.15 on 2026-06-26 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_scraperschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('launched', 'Launched'), ('skipped_in_flight', 'Skipped — run already in progress'), ('skipped_maintenance', 'Skipped — in maintenance'), ('skipped_disabled', 'Skipped — schedule disabled'), ('failed', 'Failed to start')], max_length=24)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.run')),
                ('scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='accounts.scraper')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scraper', '-created_at'], name='accounts_sc_scraper_9605c9_idx')],
            },
        ),
    ]
