# Generated by Django 5.2.15 on 2026-06-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_south_africa_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('running', 'Running'), ('stopped', 'Stopped'), ('queued', 'Queued')], default='success', max_length=12),
        ),
    ]
