# Generated by Django 5.2.15 on 2026-06-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleevent',
            name='outcome',
            field=models.CharField(choices=[('launched', 'Launched'), ('queued', 'Queued'), ('skipped_in_flight', 'Skipped — run already in progress'), ('skipped_maintenance', 'Skipped — in maintenance'), ('skipped_disabled', 'Skipped — schedule disabled'), ('failed', 'Failed to start')], max_length=24),
        ),
    ]
