# Generated by Django 5.2.15 on 2026-06-29 13:21

from django.db import migrations, models

# Hysteresis watermark — kept in lockstep with accounts.views. Inlined as a
# literal (not imported) so the migration stays decoupled from runtime code.
REQUEST_THREAD_RESUME_LOW = 10

# Mirror of Scraper.worker_count's clamp bounds (accounts.models). Inlined
# because historical migration models don't carry model properties/constants.
THREADS_MIN = 1
THREADS_MAX = 16
THREADS_DEFAULT = 5


def _worker_count(scraper):
    """Replicate ``Scraper.worker_count`` from the historical ``threads`` field."""
    value = scraper.threads or THREADS_DEFAULT
    return max(THREADS_MIN, min(value, THREADS_MAX))


def _seed_queue_gate(apps, schema_editor):
    """Reconcile the request-thread gate from the live thread count.

    This migration is exactly the "deploy/migration that lands mid-load" moment
    the gate's open-default mishandles. We rebuild the gate conservatively from
    the RUNNING runs so we don't trust the open default while jobs are mid-band:
    only a drained-to-LOW thread count is safely "open"; anything above starts
    closed so the queue drains before re-admitting. ``seeded`` is set so the
    dispatcher won't re-reconcile on its first pass.
    """
    QueueState = apps.get_model("accounts", "QueueState")
    Run = apps.get_model("accounts", "Run")

    # Browser runs hold the host alone and contribute 0 to the request-thread
    # budget; resolve which slugs are browser-based from the live registry.
    try:
        from accounts.live_scrapers import registry

        browser_slugs = {
            slug
            for slug, spec in registry.SPECS.items()
            if getattr(spec, "uses_browser", False)
        }
    except Exception:  # noqa: BLE001 — never let registry shape changes break migrate
        browser_slugs = set()

    threads_in_use = 0
    running = Run.objects.filter(status="running").select_related("scraper")
    for run in running:
        if run.scraper.slug in browser_slugs:
            continue
        threads_in_use += _worker_count(run.scraper)

    # Historical models don't carry the class-level SINGLETON_ID, so use the
    # literal pk=1 the QueueState singleton always uses.
    gate, _ = QueueState.objects.get_or_create(pk=1)
    gate.request_gate_open = threads_in_use <= REQUEST_THREAD_RESUME_LOW
    gate.seeded = True
    gate.save(update_fields=["request_gate_open", "seeded", "updated_at"])


def _noop_reverse(apps, schema_editor):
    """No reverse data step — dropping the column (below) already reverts it."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_queuestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuestate',
            name='seeded',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_seed_queue_gate, _noop_reverse),
    ]
