# Generated by Django 5.2.15 on 2026-06-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_queuestate_seeded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('ticket_created', 'New ticket'), ('comment_added', 'New comment'), ('status_changed', 'Status changed'), ('mentioned', 'Mention')], default='ticket_created', max_length=20),
        ),
    ]
