# Generated by Django 5.2.15 on 2026-06-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('qa_review', 'QA Review'), ('done', 'Done')], default='todo', max_length=16),
        ),
    ]
