# Generated by Django 5.2.15 on 2026-07-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_generalconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'Processing'), ('qa_review', 'QA'), ('done', 'Done')], default='todo', max_length=16),
        ),
    ]
